### PR TITLE
adding x55

### PR DESCRIPTION
**Pull request by thenameisluk**

### CODE REVIEW

**Comment by thenameisluk** [comment]
some basic files added
uboot repo already up

kernel on the way

also all the other scripts need to be implemented

**Comment by thenameisluk** [comment]
the thing can be viewed here
https://github.com/thenameisluk/imagebuilder/tree/for-merge/systems/console_x55

**Comment by thenameisluk** [comment]
details https://github.com/hexdump0815/imagebuilder/issues/209#issuecomment-2460856466

**Comment by thenameisluk** [comment]
@hexdump0815 can i add gdisk gdisk-partitions.txt as alternative for fdisk gpt-partitions.txt
since i need partition naming capability which it doesn't provide?

**Comment by thenameisluk** [comment]
@hexdump0815 i still need to add some notes and look into joypad not working but other than that it looks ok

**Comment by thenameisluk** [comment]
also the screen is rotated but i'll just probably joink the kukui thingy tommorow

**Comment by thenameisluk** [comment]
also i've taken out part that creates swap
because btrfs one doesn't work in trixie anymore

**Comment by thenameisluk** [comment]
i'll need to add gamepad to gamepad to joypad since the onboard one isn't really standard one

also maybe configuration file and make it universal

**Comment by hexdump0815** [comment]
what exactly is the problem with btrfs swap in trixie?

**Comment by thenameisluk** [comment]
@hexdump0815 
the command ```btrfs property set ... compression none```
failes
```
#>  export MOUNT_POINT=.
#>  btrfs subvolume create ${MOUNT_POINT}/swap
Create subvolume './swap'
#>  chmod 755 ${MOUNT_POINT}/swap
#>  chattr -R +C ${MOUNT_POINT}/swap
#>  btrfs property set ${MOUNT_POINT}/swap compression none
ERROR: failed to set compression for ./swap: Invalid argument
#> btrfs property set ${MOUNT_POINT}/swap/file.0 compression none
ERROR: failed to set compression for ./swap/file.0: Invalid argument
#>  truncate -s 0 ${MOUNT_POINT}/swap/file.0
#>  fallocate -l 512M ${MOUNT_POINT}/swap/file.0
  chmod 600 ${MOUNT_POINT}/swap/file.0
#>  /usr/sbin/mkswap -L swapfile.0 ${MOUNT_POINT}/swap/file.0
Setting up swapspace version 1, size = 512 MiB (536866816 bytes)
LABEL=swapfile.0, UUID=ae7d8e80-e994-464c-8efc-9b7738dfe59d
```
likely it's taking diffrent arguemnts

**Comment by thenameisluk** [comment]
as suggested [here](https://forum.endeavouros.com/t/cant-set-swapfile-on-btrfs-compression-to-none/51512/2)
```
btrfs filesystem mkswapfile --size 4g --uuid clear /swap/swapfile
```
can be a replacement

**Comment by thenameisluk** [comment]
@hexdump0815 since it doesn't seam to be merged soon

can i add additional screen rotation docs and [notes](https://github.com/hexdump0815/imagebuilder/issues/182#issuecomment-2495672934) to this PR? (i don't want to create separate one cause of conflicts)

**Comment by hexdump0815** [comment]
@thenameisluk - if the changes are for console_x55 then sure please add them ... if they are of more generic nature then please create a new pr as they should be outside of the systems/console_x55 tree and thus there should be no conflicts ... i'll try to get this checked and merged until including next weekend hopefully - sorry for the delay, but sadly still very minimal time right now

the btrfs swap file creation replacement looks very nice - could you maybe test if it works and if yes create a pr for it in the image creation and the recreate swap scripts?

**Comment by thenameisluk** [comment]
i'm a bit busy this week due to uni exam stuff
but will try to get the second pr ready tomorrow

also about the swap
i'm not sure if the new swap command works on bookworm
it will only require updating when we switch vt to trixie
so it's something to better leave alone for now so there is no mess
it's one line of code (per file) anyway

**Comment by hexdump0815** [comment]
take your time - there is no hurry at all ... and thanks once more for all your effort and support

**Review by hexdump0815 — APPROVED** [review]
looks very good - sorry for the delay of the merge

**Pull request merged**
