### PR TITLE
adding rg552 and updating x55

### PR DESCRIPTION
**Pull request by thenameisluk**
just need to test the image rq
but  it's basically done

### CODE REVIEW

**Comment by thenameisluk** [comment]
booted successfully
image

**Comment by thenameisluk** [comment]
booted successfully
image

**Comment by thenameisluk** [comment]
can confirm freshly built image boots without any visible issue
seams ready for review

**Comment by hexdump0815** [comment]
cool - thanks a lot - i'll review latest on the weekend

**Comment by thenameisluk** [comment]
just quick note
've included x55 here because both share joypad and uboot/kernel repo an all related stuff was updated
joypad-x55 became just joypad
rk36xx kernel became rk3xxx
an same with uboot

in theory extended version of joypad can be shipped for tv boxes to lep ppl control their mouse with remote or gamepad but that's just an idea

**Comment by thenameisluk** [comment]
@hexdump0815
would making by default /script/fan_speed execute as owner and making it owned by root be ok?
it would be easier for ppl to setup controlls for it without having to play around with permissions
for example a button in gnome shell to toggle fan speed

**Comment by thenameisluk** [comment]
never mind
https://github.com/hexdump0815/imagebuilder/issues/276#issuecomment-2558203026

**Comment by thenameisluk** [comment]
for whatever reason i can't get splash screen working ;-;
not clues, it just doesn't show up even with quiet and splash

**Comment by thenameisluk** [comment]
've found the fix
additionally you need to append ```plymouth.ignore-serial-consoles``` because yes

**Comment by hexdump0815** [comment]
@thenameisluk - i looked though the pr and it looks fine to me ... only two things i noticed not directly in the pr but in the linked kernel build readme files:
- the dtb should also be installed with a version number, so that we in theory can also have two different kernel versions with two different dtb files - my suggestion would be to go with the path used so far for everything else: dtb-<version-string>/the.dtb even if there is only one dtb file in the dir in the end for this system, but this way it would be consistent across all systems (this would apply to both the x55 and the rg552)
- so far i always used xyz-abc for the version string, i.e. xyz=stb for the kernel tree used like stable (or rkc for the rockchip legacy kernel tree for example etc.) and abc=x55 for the specific system kernel built from this tree and i always kept it with three letters/digits for each all the time to keep the names still reasonably short and the structure consistent (which resulted in some creativity in the names used like 616 for h616 sometimes, which i do not see as a problem) - would it be ok to change the rg552 one to something following the same naming schema like 552 or so?

best wishes - hexdump

**Comment by thenameisluk** [comment]
will fix up the dtb stuff and push changes

when it comes to doing rg552 -> 552 or rk3 or similar

if nesesery i would probably prefer to name it "rg5" (from its full name : retro game 552) since the fact it's rg552 specific, which makes it different from other rk devices and using numbers would make the name confusing

**Comment by thenameisluk** [comment]
for rg552 name changed, dtb moved and tested

for x55 might as well move to 6.12 kernel ☕

**Comment by thenameisluk** [comment]
this one is not **yet** tested

**Comment by thenameisluk** [comment]
tested, not visible issues
image

**Comment by thenameisluk** [comment]
unless there are any other issues
should be ready ro merge

**Review by hexdump0815 — APPROVED** [review]
looks good

**Comment by hexdump0815** [comment]
merged - thanks a lot!

**Pull request merged**
