### PR TITLE
lenovo miix 630 works with 221101-01 

### PR DESCRIPTION
**Pull request by Titoot**
it works fine, first boot it just hanged but restarted then it worked fine, obv had to connect external keyboard and mouse because the internals doesn't
if there's anything you want me to test let me know
image

### CODE REVIEW

**Comment by hexdump0815** [comment]
cool - thanks a lot for the feedback - will merge it in a minute ...

**Comment by hexdump0815** [comment]
@Titoot - its always a good idea to leave windows on the machine for firmware-updates etc. ... i think i read somewhere that for lenovo you can open some special ticket somewhere at lenovo support to get access to restore images - there is no easy or official way to restore any windows on arm machines as far as i know

**Comment by hexdump0815** [comment]
@Titoot - i think this is where i read it: https://oftc.irclog.whitequark.org/aarch64-laptops/2023-01-04

**Comment by Titoot** [comment]
@hexdump0815 - oh thanks for looking it up!
I literally tried everything to get it working but nothing worked (or functional enough), and no support from Lenovo, and I did try to ask at their forum so yeah.
but really thanks, bro.

**Pull request merged**
